# Site settings
title: Coova
description: > # this means to ignore newlines until "baseurl:"
 Open Source Captive Portal Access Controller and RADIUS Software.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://coova.org" # the base hostname & protocol for your site
github_username:  coova

# Build settings
markdown: kramdown
